app:
  name: swamy app
  msg: welcome to ${app.name}

my:
  greeting: Hello-from-properties - client 1111

db:
  connection: connection-string-here
  host: localhost
  port: 1527

spring:
  cloud:
    config:
      uri: http://localhost:8888

  application:
    name: spring-config-client

logging:
  level:
    root: DEBUG
# Spring Boot Actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"